require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Call4CareDoc' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'Call4CareDocTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'Call4CareDoc-tvOS' do
  # Pods for Call4CareDoc-tvOS

  target 'Call4CareDoc-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
